### ISSUE TITLE
release page empty

### ISSUE THREAD

**Issue by c33s** [KonradIT/mmt#1]
the installation readme says "download from the release page" sadly there are no releases (yet?).

**Comment by astrodad** [comment]
Would it be possible to include some instructions to build it ourselves?

**Comment by KonradIT** [comment]
For building:

```
go build .
```

(On Windows, on Mac and Linux I need to figure out how to isolate a windows-only dependency).

**Comment by astrodad** [comment]
Looks like I ran into that issue:

> go build github.com/konradit/gowpd: build constraints exclude all Go files in /Users/javier/go/pkg/mod/github.com/konradit/gowpd@v0.0.0-20210412221322-abb981a4530d

**Comment by KonradIT** [comment]
Hi, I've removed the offending dependency. Try again.

**Comment by c33s** [comment]
would still be great to autobuild it with github actions and publish it on the release page.

**Comment by KonradIT** [comment]
Just pushed a first release on the releases page, will do it manually for now.
