### ISSUE TITLE
Unable to get connect method working - HERO 5 Session

### ISSUE THREAD

**Issue by daktak** [KonradIT/mmt#10]
This is the result, camera has 43 videos. I can see them in GoProDashboard for example.
```
gopro mmt import -x connect -o . -c gopro -i 10.5.5.9 -v
GoPro Tool for Linux
To see a list of commands and syntax available run: gopro help
Checking dependencies...
+----------------+---------------+--------+
| FILES IMPORTED | FILES SKIPPED | ERRORS |
+----------------+---------------+--------+
|              0 |             0 |      0 |
+----------------+---------------+--------+
##try without specifying ip address
gopro mmt import -x connect -o . -c gopro -v
GoPro Tool for Linux
To see a list of commands and syntax available run: gopro help
Checking dependencies...
X Something went wrong
  Get "http:///gp/gpTurbo?p=1": http: no Host in request URL

curl 'http://10.5.5.9/gp/gpTurbo?p=1'
Error 404: Not Found

```

**Comment by daktak** [comment]
Using the below for the time being
`wget -c -A .MP4 -r -nH --cut-dirs=3 --no-parent -e robots=off http://10.5.5.9/videos/DCIM/100GOPRO/`

**Comment by KonradIT** [comment]
Hi, this connect mode is only for GoPro Connect mode available on Hero9/10/11 cameras. But it could be opened to normal WiFi operation as well, just think that it'll be too slow for getting a ton of media.

**Comment by daktak** [comment]
watch -c -n 1 wol -i 10.5.5.9 f6:dd:9e:ma:ca:dd -p9
I did wol every sec and wget, worked quite well.

**Comment by KonradIT** [comment]
For HERO5 Session, it uses MTP for USB. It was supported at some point, but unfortunately broke building on some systems. 

Neither MTP or GoPro wireless offload will be supported by me, feel free to add them yourself.

**Comment by daktak** [comment]
https://github.com/KonradIT/mmt/pull/26
