### ISSUE TITLE
Go Pro Session (1st gen) supported?

### ISSUE THREAD

**Issue by D3rpi** [KonradIT/mmt#6]
Is the GoPro Session 1st gen supported by the tool?
Tried to use the tool but my GoPro Session did not show up when I ran the list command. It only showed the 2 partitions I have on my hard drive.
Go Pro session is accessible by Windows manager but also does not have an assigned drive. 
Address: This PC\HERO4 Session\External Memory

**Comment by KonradIT** [comment]
That's because it's mounted as an MTP drive, which the program does not accept. Use an SD card reader.

**Comment by D3rpi** [comment]
Gotcha. Thanks for the clarification. 
I'll close this
