### ISSUE TITLE
Clarification on config usage

### ISSUE THREAD

**Issue by psukys** [KonradIT/mmt#8]
from help string, mmt states:
```
      --config string   config file (default is $HOME/.mmt.yaml)
```
yet it's not entirely clear what the structure of config should be. Are there any guidelines for this?

**Comment by daktak** [comment]
https://github.com/KonradIT/mmt/pull/29

parameter: value
ie
```
camera: gopro
output: /home/user/Videos
input: 10.5.5.9
connection: connect
```

**Comment by KonradIT** [comment]
True, now the config file is supported.
